items:
- uid: System.ServiceModel.BasicHttpsSecurity
  commentId: T:System.ServiceModel.BasicHttpsSecurity
  id: BasicHttpsSecurity
  parent: System.ServiceModel
  children:
  - System.ServiceModel.BasicHttpsSecurity.Mode
  - System.ServiceModel.BasicHttpsSecurity.Transport
  langs:
  - csharp
  - vb
  name: BasicHttpsSecurity
  fullName: System.ServiceModel.BasicHttpsSecurity
  type: Class
  source:
    remote:
      path: src/System.ServiceModel.Http/ref/System.ServiceModel.Http.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: BasicHttpsSecurity
    path: src/System.ServiceModel.Http/ref/System.ServiceModel.Http.cs
    startLine: 44
  assemblies:
  - System.ServiceModel.Http
  namespace: System.ServiceModel
  summary: "\n<p>Specifies basic https security settings.</p>\n"
  syntax:
    content: public sealed class BasicHttpsSecurity
    content.vb: Public NotInheritable Class BasicHttpsSecurity
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
  nameWithType: BasicHttpsSecurity
- uid: System.ServiceModel.BasicHttpsSecurity.Mode
  commentId: P:System.ServiceModel.BasicHttpsSecurity.Mode
  id: Mode
  parent: System.ServiceModel.BasicHttpsSecurity
  langs:
  - csharp
  - vb
  name: Mode
  fullName: System.ServiceModel.BasicHttpsSecurity.Mode
  type: Property
  source:
    remote:
      path: src/System.ServiceModel.Http/ref/System.ServiceModel.Http.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: Mode
    path: src/System.ServiceModel.Http/ref/System.ServiceModel.Http.cs
    startLine: 47
  assemblies:
  - System.ServiceModel.Http
  namespace: System.ServiceModel
  summary: "\n<p>Gets or sets the security mode for a basicHttpsBinding binding.</p>\n"
  syntax:
    content: public BasicHttpsSecurityMode Mode { get; set; }
    content.vb: Public Property Mode As BasicHttpsSecurityMode
    parameters: []
    return:
      type: System.ServiceModel.BasicHttpsSecurityMode
      description: "\n<p>The security mode for a basicHttpsBinding binding.</p>\n"
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  nameWithType: BasicHttpsSecurity.Mode
- uid: System.ServiceModel.BasicHttpsSecurity.Transport
  commentId: P:System.ServiceModel.BasicHttpsSecurity.Transport
  id: Transport
  parent: System.ServiceModel.BasicHttpsSecurity
  langs:
  - csharp
  - vb
  name: Transport
  fullName: System.ServiceModel.BasicHttpsSecurity.Transport
  type: Property
  source:
    remote:
      path: src/System.ServiceModel.Http/ref/System.ServiceModel.Http.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: Transport
    path: src/System.ServiceModel.Http/ref/System.ServiceModel.Http.cs
    startLine: 48
  assemblies:
  - System.ServiceModel.Http
  namespace: System.ServiceModel
  summary: "\n<p>Gets the transport-level security settings for a basicHttpsBinding binding.</p>\n"
  syntax:
    content: public HttpTransportSecurity Transport { get; set; }
    content.vb: Public Property Transport As HttpTransportSecurity
    parameters: []
    return:
      type: System.ServiceModel.HttpTransportSecurity
      description: "\n<p>The transport-level security settings for a basicHttpsBinding binding.</p>\n"
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  nameWithType: BasicHttpsSecurity.Transport
references:
- uid: System.ServiceModel
  isExternal: false
  name: System.ServiceModel
  fullName: System.ServiceModel
  commentId: N:System.ServiceModel
  nameWithType: System.ServiceModel
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
  commentId: T:System.Object
  nameWithType: Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  commentId: M:System.Object.ToString
  nameWithType: Object.ToString()
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  commentId: M:System.Object.Equals(System.Object)
  nameWithType: Object.Equals(Object)
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  commentId: M:System.Object.Equals(System.Object,System.Object)
  nameWithType: Object.Equals(Object, Object)
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  commentId: M:System.Object.GetHashCode
  nameWithType: Object.GetHashCode()
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  commentId: M:System.Object.GetType
  nameWithType: Object.GetType()
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  commentId: M:System.Object.MemberwiseClone
  nameWithType: Object.MemberwiseClone()
- uid: System
  isExternal: false
  name: System
  fullName: System
  commentId: N:System
  nameWithType: System
- uid: System.ServiceModel.BasicHttpsSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: BasicHttpsSecurityMode
  fullName: System.ServiceModel.BasicHttpsSecurityMode
  commentId: T:System.ServiceModel.BasicHttpsSecurityMode
  nameWithType: BasicHttpsSecurityMode
- uid: System.ServiceModel.HttpTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: HttpTransportSecurity
  fullName: System.ServiceModel.HttpTransportSecurity
  commentId: T:System.ServiceModel.HttpTransportSecurity
  nameWithType: HttpTransportSecurity
