items:
- uid: System.Net.Security
  commentId: N:System.Net.Security
  id: System.Net.Security
  children:
  - System.Net.Security.AuthenticatedStream
  - System.Net.Security.AuthenticationLevel
  - System.Net.Security.EncryptionPolicy
  - System.Net.Security.LocalCertificateSelectionCallback
  - System.Net.Security.NegotiateStream
  - System.Net.Security.ProtectionLevel
  - System.Net.Security.RemoteCertificateValidationCallback
  - System.Net.Security.SslPolicyErrors
  - System.Net.Security.SslStream
  langs:
  - csharp
  - vb
  name: System.Net.Security
  nameWithType: System.Net.Security
  fullName: System.Net.Security
  type: Namespace
  assemblies:
  - System.Net.Primitives
references:
- uid: System.Net.Security.AuthenticationLevel
  commentId: T:System.Net.Security.AuthenticationLevel
  parent: System.Net.Security
  isExternal: false
  name: AuthenticationLevel
  nameWithType: AuthenticationLevel
  fullName: System.Net.Security.AuthenticationLevel
- uid: System.Net.Security.SslPolicyErrors
  commentId: T:System.Net.Security.SslPolicyErrors
  parent: System.Net.Security
  isExternal: false
  name: SslPolicyErrors
  nameWithType: SslPolicyErrors
  fullName: System.Net.Security.SslPolicyErrors
- uid: System.Net.Security.AuthenticatedStream
  commentId: T:System.Net.Security.AuthenticatedStream
  parent: System.Net.Security
  isExternal: false
  name: AuthenticatedStream
  nameWithType: AuthenticatedStream
  fullName: System.Net.Security.AuthenticatedStream
- uid: System.Net.Security.EncryptionPolicy
  commentId: T:System.Net.Security.EncryptionPolicy
  parent: System.Net.Security
  isExternal: false
  name: EncryptionPolicy
  nameWithType: EncryptionPolicy
  fullName: System.Net.Security.EncryptionPolicy
- uid: System.Net.Security.LocalCertificateSelectionCallback
  commentId: T:System.Net.Security.LocalCertificateSelectionCallback
  parent: System.Net.Security
  isExternal: false
  name: LocalCertificateSelectionCallback
  nameWithType: LocalCertificateSelectionCallback
  fullName: System.Net.Security.LocalCertificateSelectionCallback
- uid: System.Net.Security.NegotiateStream
  commentId: T:System.Net.Security.NegotiateStream
  isExternal: false
  name: NegotiateStream
  nameWithType: NegotiateStream
  fullName: System.Net.Security.NegotiateStream
- uid: System.Net.Security.ProtectionLevel
  commentId: T:System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.Net.Security.RemoteCertificateValidationCallback
  commentId: T:System.Net.Security.RemoteCertificateValidationCallback
  parent: System.Net.Security
  isExternal: false
  name: RemoteCertificateValidationCallback
  nameWithType: RemoteCertificateValidationCallback
  fullName: System.Net.Security.RemoteCertificateValidationCallback
- uid: System.Net.Security.SslStream
  commentId: T:System.Net.Security.SslStream
  isExternal: false
  name: SslStream
  nameWithType: SslStream
  fullName: System.Net.Security.SslStream
- uid: System.Net.Security
  commentId: N:System.Net.Security
  isExternal: false
  name: System.Net.Security
  nameWithType: System.Net.Security
  fullName: System.Net.Security
