### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Security
  commentId: N:System.ServiceModel.Security
  id: System.ServiceModel.Security
  children:
  - System.ServiceModel.Security.BasicSecurityProfileVersion
  - System.ServiceModel.Security.HttpDigestClientCredential
  - System.ServiceModel.Security.MessageSecurityException
  - System.ServiceModel.Security.SecureConversationVersion
  - System.ServiceModel.Security.SecurityAccessDeniedException
  - System.ServiceModel.Security.SecurityPolicyVersion
  - System.ServiceModel.Security.SecurityVersion
  - System.ServiceModel.Security.TrustVersion
  - System.ServiceModel.Security.UserNamePasswordClientCredential
  - System.ServiceModel.Security.WindowsClientCredential
  - System.ServiceModel.Security.X509CertificateInitiatorClientCredential
  - System.ServiceModel.Security.X509CertificateRecipientClientCredential
  - System.ServiceModel.Security.X509CertificateValidationMode
  - System.ServiceModel.Security.X509ServiceCertificateAuthentication
  langs:
  - csharp
  - vb
  name: System.ServiceModel.Security
  nameWithType: System.ServiceModel.Security
  fullName: System.ServiceModel.Security
  type: Namespace
  assemblies:
  - System.ServiceModel.Primitives
references:
- uid: System.ServiceModel.Security.HttpDigestClientCredential
  commentId: T:System.ServiceModel.Security.HttpDigestClientCredential
  parent: System.ServiceModel.Security
  isExternal: false
  name: HttpDigestClientCredential
  nameWithType: HttpDigestClientCredential
  fullName: System.ServiceModel.Security.HttpDigestClientCredential
- uid: System.ServiceModel.Security.MessageSecurityException
  commentId: T:System.ServiceModel.Security.MessageSecurityException
  isExternal: false
  name: MessageSecurityException
  nameWithType: MessageSecurityException
  fullName: System.ServiceModel.Security.MessageSecurityException
- uid: System.ServiceModel.Security.SecurityAccessDeniedException
  commentId: T:System.ServiceModel.Security.SecurityAccessDeniedException
  isExternal: false
  name: SecurityAccessDeniedException
  nameWithType: SecurityAccessDeniedException
  fullName: System.ServiceModel.Security.SecurityAccessDeniedException
- uid: System.ServiceModel.Security.UserNamePasswordClientCredential
  commentId: T:System.ServiceModel.Security.UserNamePasswordClientCredential
  parent: System.ServiceModel.Security
  isExternal: false
  name: UserNamePasswordClientCredential
  nameWithType: UserNamePasswordClientCredential
  fullName: System.ServiceModel.Security.UserNamePasswordClientCredential
- uid: System.ServiceModel.Security.WindowsClientCredential
  commentId: T:System.ServiceModel.Security.WindowsClientCredential
  parent: System.ServiceModel.Security
  isExternal: false
  name: WindowsClientCredential
  nameWithType: WindowsClientCredential
  fullName: System.ServiceModel.Security.WindowsClientCredential
- uid: System.ServiceModel.Security.X509ServiceCertificateAuthentication
  commentId: T:System.ServiceModel.Security.X509ServiceCertificateAuthentication
  parent: System.ServiceModel.Security
  isExternal: false
  name: X509ServiceCertificateAuthentication
  nameWithType: X509ServiceCertificateAuthentication
  fullName: System.ServiceModel.Security.X509ServiceCertificateAuthentication
- uid: System.ServiceModel.Security.X509CertificateInitiatorClientCredential
  commentId: T:System.ServiceModel.Security.X509CertificateInitiatorClientCredential
  parent: System.ServiceModel.Security
  isExternal: false
  name: X509CertificateInitiatorClientCredential
  nameWithType: X509CertificateInitiatorClientCredential
  fullName: System.ServiceModel.Security.X509CertificateInitiatorClientCredential
- uid: System.ServiceModel.Security.X509CertificateRecipientClientCredential
  commentId: T:System.ServiceModel.Security.X509CertificateRecipientClientCredential
  parent: System.ServiceModel.Security
  isExternal: false
  name: X509CertificateRecipientClientCredential
  nameWithType: X509CertificateRecipientClientCredential
  fullName: System.ServiceModel.Security.X509CertificateRecipientClientCredential
- uid: System.ServiceModel.Security.X509CertificateValidationMode
  commentId: T:System.ServiceModel.Security.X509CertificateValidationMode
  parent: System.ServiceModel.Security
  isExternal: false
  name: X509CertificateValidationMode
  nameWithType: X509CertificateValidationMode
  fullName: System.ServiceModel.Security.X509CertificateValidationMode
- uid: System.ServiceModel.Security.BasicSecurityProfileVersion
  commentId: T:System.ServiceModel.Security.BasicSecurityProfileVersion
  parent: System.ServiceModel.Security
  isExternal: false
  name: BasicSecurityProfileVersion
  nameWithType: BasicSecurityProfileVersion
  fullName: System.ServiceModel.Security.BasicSecurityProfileVersion
- uid: System.ServiceModel.Security.SecureConversationVersion
  commentId: T:System.ServiceModel.Security.SecureConversationVersion
  parent: System.ServiceModel.Security
  isExternal: false
  name: SecureConversationVersion
  nameWithType: SecureConversationVersion
  fullName: System.ServiceModel.Security.SecureConversationVersion
- uid: System.ServiceModel.Security.SecurityPolicyVersion
  commentId: T:System.ServiceModel.Security.SecurityPolicyVersion
  parent: System.ServiceModel.Security
  isExternal: false
  name: SecurityPolicyVersion
  nameWithType: SecurityPolicyVersion
  fullName: System.ServiceModel.Security.SecurityPolicyVersion
- uid: System.ServiceModel.Security.SecurityVersion
  commentId: T:System.ServiceModel.Security.SecurityVersion
  parent: System.ServiceModel.Security
  isExternal: false
  name: SecurityVersion
  nameWithType: SecurityVersion
  fullName: System.ServiceModel.Security.SecurityVersion
- uid: System.ServiceModel.Security.TrustVersion
  commentId: T:System.ServiceModel.Security.TrustVersion
  parent: System.ServiceModel.Security
  isExternal: false
  name: TrustVersion
  nameWithType: TrustVersion
  fullName: System.ServiceModel.Security.TrustVersion
- uid: System.ServiceModel.Security
  commentId: N:System.ServiceModel.Security
  isExternal: false
  name: System.ServiceModel.Security
  nameWithType: System.ServiceModel.Security
  fullName: System.ServiceModel.Security
