items:
- uid: System.ServiceModel.NetTcpSecurity
  commentId: T:System.ServiceModel.NetTcpSecurity
  id: NetTcpSecurity
  parent: System.ServiceModel
  children:
  - System.ServiceModel.NetTcpSecurity.#ctor
  - System.ServiceModel.NetTcpSecurity.Message
  - System.ServiceModel.NetTcpSecurity.Mode
  - System.ServiceModel.NetTcpSecurity.Transport
  langs:
  - csharp
  - vb
  name: NetTcpSecurity
  fullName: System.ServiceModel.NetTcpSecurity
  type: Class
  source:
    remote:
      path: src/System.Private.ServiceModel/src/System/ServiceModel/NetTcpSecurity.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: NetTcpSecurity
    path: src/System.Private.ServiceModel/src/System/ServiceModel/NetTcpSecurity.cs
    startLine: 12
  assemblies:
  - System.ServiceModel.NetTcp
  namespace: System.ServiceModel
  summary: "\n<p>Specifies the types of transport-level and message-level security used by an endpoint configured with a <xref href=\"System.ServiceModel.NetTcpBinding\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  syntax:
    content: public sealed class NetTcpSecurity
    content.vb: Public NotInheritable Class NetTcpSecurity
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
  nameWithType: NetTcpSecurity
- uid: System.ServiceModel.NetTcpSecurity.#ctor
  commentId: M:System.ServiceModel.NetTcpSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.NetTcpSecurity
  langs:
  - csharp
  - vb
  name: NetTcpSecurity()
  fullName: System.ServiceModel.NetTcpSecurity.NetTcpSecurity()
  type: Constructor
  source:
    remote:
      path: src/System.Private.ServiceModel/src/System/ServiceModel/NetTcpSecurity.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: .ctor
    path: src/System.Private.ServiceModel/src/System/ServiceModel/NetTcpSecurity.cs
    startLine: 20
  assemblies:
  - System.ServiceModel.NetTcp
  namespace: System.ServiceModel
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.ServiceModel.NetTcpSecurity\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  syntax:
    content: public NetTcpSecurity()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  nameWithType: NetTcpSecurity.NetTcpSecurity()
- uid: System.ServiceModel.NetTcpSecurity.Message
  commentId: P:System.ServiceModel.NetTcpSecurity.Message
  id: Message
  parent: System.ServiceModel.NetTcpSecurity
  langs:
  - csharp
  - vb
  name: Message
  fullName: System.ServiceModel.NetTcpSecurity.Message
  type: Property
  source:
    remote:
      path: src/System.Private.ServiceModel/src/System/ServiceModel/NetTcpSecurity.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: Message
    path: src/System.Private.ServiceModel/src/System/ServiceModel/NetTcpSecurity.cs
    startLine: 59
  assemblies:
  - System.ServiceModel.NetTcp
  namespace: System.ServiceModel
  summary: "\n<p>Gets the type of message-level security requirements for a service configured with a <xref href=\"System.ServiceModel.NetTcpBinding\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  syntax:
    content: public MessageSecurityOverTcp Message { get; set; }
    content.vb: Public Property Message As MessageSecurityOverTcp
    parameters: []
    return:
      type: System.ServiceModel.MessageSecurityOverTcp
      description: "\n<p>The <xref href=\"System.ServiceModel.MessageSecurityOverTcp\" data-throw-if-not-resolved=\"false\"></xref> that indicates the type of message-level security requirements for an endpoint.</p>\n"
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  nameWithType: NetTcpSecurity.Message
- uid: System.ServiceModel.NetTcpSecurity.Mode
  commentId: P:System.ServiceModel.NetTcpSecurity.Mode
  id: Mode
  parent: System.ServiceModel.NetTcpSecurity
  langs:
  - csharp
  - vb
  name: Mode
  fullName: System.ServiceModel.NetTcpSecurity.Mode
  type: Property
  source:
    remote:
      path: src/System.Private.ServiceModel/src/System/ServiceModel/NetTcpSecurity.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: Mode
    path: src/System.Private.ServiceModel/src/System/ServiceModel/NetTcpSecurity.cs
    startLine: 39
  assemblies:
  - System.ServiceModel.NetTcp
  namespace: System.ServiceModel
  summary: "\n<p>Gets or sets whether message-level security and transport-level security are used by an endpoint configured with a <xref href=\"System.ServiceModel.NetTcpBinding\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  syntax:
    content: public SecurityMode Mode { get; set; }
    content.vb: Public Property Mode As SecurityMode
    parameters: []
    return:
      type: System.ServiceModel.SecurityMode
      description: "\n<p>A value of the <xref href=\"System.ServiceModel.SecurityMode\" data-throw-if-not-resolved=\"false\"></xref> that indicates whether message-level security or transport-level security is used by an endpoint. The default value is <xref href=\"System.ServiceModel.SecurityMode.Transport\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "\n<p>The value is not defined.</p>\n"
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  nameWithType: NetTcpSecurity.Mode
- uid: System.ServiceModel.NetTcpSecurity.Transport
  commentId: P:System.ServiceModel.NetTcpSecurity.Transport
  id: Transport
  parent: System.ServiceModel.NetTcpSecurity
  langs:
  - csharp
  - vb
  name: Transport
  fullName: System.ServiceModel.NetTcpSecurity.Transport
  type: Property
  source:
    remote:
      path: src/System.Private.ServiceModel/src/System/ServiceModel/NetTcpSecurity.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: Transport
    path: src/System.Private.ServiceModel/src/System/ServiceModel/NetTcpSecurity.cs
    startLine: 53
  assemblies:
  - System.ServiceModel.NetTcp
  namespace: System.ServiceModel
  summary: "\n<p>Gets the type of message-level security requirements for an endpoint configured with a <xref href=\"System.ServiceModel.NetTcpBinding\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  syntax:
    content: public TcpTransportSecurity Transport { get; set; }
    content.vb: Public Property Transport As TcpTransportSecurity
    parameters: []
    return:
      type: System.ServiceModel.TcpTransportSecurity
      description: "\n<p>The <xref href=\"System.ServiceModel.TcpTransportSecurity\" data-throw-if-not-resolved=\"false\"></xref> that indicates the type of transport-level security requirements for an endpoint.</p>\n"
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  nameWithType: NetTcpSecurity.Transport
references:
- uid: System.ServiceModel
  isExternal: false
  name: System.ServiceModel
  fullName: System.ServiceModel
  nameWithType: System.ServiceModel
  commentId: N:System.ServiceModel
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
  nameWithType: Object
  commentId: T:System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  nameWithType: Object.ToString()
  commentId: M:System.Object.ToString
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  nameWithType: Object.Equals(Object)
  commentId: M:System.Object.Equals(System.Object)
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  nameWithType: Object.Equals(Object, Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  nameWithType: Object.ReferenceEquals(Object, Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  nameWithType: Object.GetHashCode()
  commentId: M:System.Object.GetHashCode
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  nameWithType: Object.GetType()
  commentId: M:System.Object.GetType
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  nameWithType: Object.MemberwiseClone()
  commentId: M:System.Object.MemberwiseClone
- uid: System
  isExternal: false
  name: System
  fullName: System
  nameWithType: System
  commentId: N:System
- uid: System.ServiceModel.MessageSecurityOverTcp
  parent: System.ServiceModel
  isExternal: false
  name: MessageSecurityOverTcp
  fullName: System.ServiceModel.MessageSecurityOverTcp
  nameWithType: MessageSecurityOverTcp
  commentId: T:System.ServiceModel.MessageSecurityOverTcp
- uid: System.ServiceModel.SecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: SecurityMode
  fullName: System.ServiceModel.SecurityMode
  nameWithType: SecurityMode
  commentId: T:System.ServiceModel.SecurityMode
- uid: System.ServiceModel.TcpTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: TcpTransportSecurity
  fullName: System.ServiceModel.TcpTransportSecurity
  nameWithType: TcpTransportSecurity
  commentId: T:System.ServiceModel.TcpTransportSecurity
- uid: System.ArgumentOutOfRangeException
  isExternal: false
  name: ArgumentOutOfRangeException
  fullName: System.ArgumentOutOfRangeException
  nameWithType: ArgumentOutOfRangeException
  commentId: T:System.ArgumentOutOfRangeException
