items:
- uid: System.ServiceModel.Channels.TcpConnectionPoolSettings
  commentId: T:System.ServiceModel.Channels.TcpConnectionPoolSettings
  id: TcpConnectionPoolSettings
  parent: System.ServiceModel.Channels
  children:
  - System.ServiceModel.Channels.TcpConnectionPoolSettings.GroupName
  - System.ServiceModel.Channels.TcpConnectionPoolSettings.IdleTimeout
  - System.ServiceModel.Channels.TcpConnectionPoolSettings.LeaseTimeout
  - System.ServiceModel.Channels.TcpConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  langs:
  - csharp
  - vb
  name: TcpConnectionPoolSettings
  fullName: System.ServiceModel.Channels.TcpConnectionPoolSettings
  type: Class
  source:
    remote:
      path: src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: TcpConnectionPoolSettings
    path: src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.cs
    startLine: 82
  assemblies:
  - System.ServiceModel.NetTcp
  namespace: System.ServiceModel.Channels
  summary: "\n<p>Represents properties that control the behavior of the TCP connection pool.</p>\n"
  syntax:
    content: public sealed class TcpConnectionPoolSettings
    content.vb: Public NotInheritable Class TcpConnectionPoolSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
  nameWithType: TcpConnectionPoolSettings
- uid: System.ServiceModel.Channels.TcpConnectionPoolSettings.GroupName
  commentId: P:System.ServiceModel.Channels.TcpConnectionPoolSettings.GroupName
  id: GroupName
  parent: System.ServiceModel.Channels.TcpConnectionPoolSettings
  langs:
  - csharp
  - vb
  name: GroupName
  fullName: System.ServiceModel.Channels.TcpConnectionPoolSettings.GroupName
  type: Property
  source:
    remote:
      path: src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: GroupName
    path: src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.cs
    startLine: 85
  assemblies:
  - System.ServiceModel.NetTcp
  namespace: System.ServiceModel.Channels
  summary: "\n<p>Gets or sets the group name of the connection pool group on the client.</p>\n"
  syntax:
    content: public string GroupName { get; set; }
    content.vb: Public Property GroupName As String
    parameters: []
    return:
      type: System.String
      description: "\n<p>The group name of the connection pool group on the client. The default name is \"default\".</p>\n"
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n<p>The value is <strong>null</strong>.</p>\n"
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  nameWithType: TcpConnectionPoolSettings.GroupName
- uid: System.ServiceModel.Channels.TcpConnectionPoolSettings.IdleTimeout
  commentId: P:System.ServiceModel.Channels.TcpConnectionPoolSettings.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Channels.TcpConnectionPoolSettings
  langs:
  - csharp
  - vb
  name: IdleTimeout
  fullName: System.ServiceModel.Channels.TcpConnectionPoolSettings.IdleTimeout
  type: Property
  source:
    remote:
      path: src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: IdleTimeout
    path: src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.cs
    startLine: 86
  assemblies:
  - System.ServiceModel.NetTcp
  namespace: System.ServiceModel.Channels
  summary: "\n<p>Gets or sets the maximum time the connection can be idle in the connection pool before being disconnected.</p>\n"
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    content.vb: Public Property IdleTimeout As TimeSpan
    parameters: []
    return:
      type: System.TimeSpan
      description: "\n<p>Returns a <xref href=\"System.TimeSpan\" data-throw-if-not-resolved=\"false\"></xref> structure that indicates the maximum time the connection can be idle in the connection pool before being disconnected.</p>\n"
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "\n<p>The value is less than zero.</p>\n"
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  nameWithType: TcpConnectionPoolSettings.IdleTimeout
- uid: System.ServiceModel.Channels.TcpConnectionPoolSettings.LeaseTimeout
  commentId: P:System.ServiceModel.Channels.TcpConnectionPoolSettings.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Channels.TcpConnectionPoolSettings
  langs:
  - csharp
  - vb
  name: LeaseTimeout
  fullName: System.ServiceModel.Channels.TcpConnectionPoolSettings.LeaseTimeout
  type: Property
  source:
    remote:
      path: src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: LeaseTimeout
    path: src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.cs
    startLine: 87
  assemblies:
  - System.ServiceModel.NetTcp
  namespace: System.ServiceModel.Channels
  summary: "\n<p>Gets or sets the time span after which a connection in the connection pool is closed.</p>\n"
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    content.vb: Public Property LeaseTimeout As TimeSpan
    parameters: []
    return:
      type: System.TimeSpan
      description: "\n<p>Returns a <xref href=\"System.TimeSpan\" data-throw-if-not-resolved=\"false\"></xref> structure that indicates the time span after which a cached TCP connection is purged from the connection pool.</p>\n"
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "\n<p>The value cannot be less than zero.</p>\n"
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  nameWithType: TcpConnectionPoolSettings.LeaseTimeout
- uid: System.ServiceModel.Channels.TcpConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  commentId: P:System.ServiceModel.Channels.TcpConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  id: MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Channels.TcpConnectionPoolSettings
  langs:
  - csharp
  - vb
  name: MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Channels.TcpConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  type: Property
  source:
    remote:
      path: src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: MaxOutboundConnectionsPerEndpoint
    path: src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.cs
    startLine: 88
  assemblies:
  - System.ServiceModel.NetTcp
  namespace: System.ServiceModel.Channels
  summary: "\n<p>Gets or sets the maximum number of outbound connections for each endpoint that is cached in the connection pool.</p>\n"
  syntax:
    content: public int MaxOutboundConnectionsPerEndpoint { get; set; }
    content.vb: Public Property MaxOutboundConnectionsPerEndpoint As Integer
    parameters: []
    return:
      type: System.Int32
      description: "\n<p>The maximum number of allowed outbound connections for each endpoint that is cached in the connection pool. The default value is 10.</p>\n"
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "\n<p>The value is less than or equal to zero.</p>\n"
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  nameWithType: TcpConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
references:
- uid: System.ServiceModel.Channels
  isExternal: false
  name: System.ServiceModel.Channels
  fullName: System.ServiceModel.Channels
  commentId: N:System.ServiceModel.Channels
  nameWithType: System.ServiceModel.Channels
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
  commentId: T:System.Object
  nameWithType: Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  commentId: M:System.Object.ToString
  nameWithType: Object.ToString()
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  commentId: M:System.Object.Equals(System.Object)
  nameWithType: Object.Equals(Object)
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  commentId: M:System.Object.Equals(System.Object,System.Object)
  nameWithType: Object.Equals(Object, Object)
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  commentId: M:System.Object.GetHashCode
  nameWithType: Object.GetHashCode()
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  commentId: M:System.Object.GetType
  nameWithType: Object.GetType()
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  commentId: M:System.Object.MemberwiseClone
  nameWithType: Object.MemberwiseClone()
- uid: System
  isExternal: false
  name: System
  fullName: System
  commentId: N:System
  nameWithType: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
  commentId: T:System.String
  nameWithType: String
- uid: System.TimeSpan
  parent: System
  isExternal: false
  name: TimeSpan
  fullName: System.TimeSpan
  commentId: T:System.TimeSpan
  nameWithType: TimeSpan
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  fullName: System.Int32
  commentId: T:System.Int32
  nameWithType: Int32
- uid: System.ArgumentNullException
  isExternal: false
  name: ArgumentNullException
  fullName: System.ArgumentNullException
  nameWithType: ArgumentNullException
  commentId: T:System.ArgumentNullException
- uid: System.ArgumentOutOfRangeException
  isExternal: false
  name: ArgumentOutOfRangeException
  fullName: System.ArgumentOutOfRangeException
  nameWithType: ArgumentOutOfRangeException
  commentId: T:System.ArgumentOutOfRangeException
