items:
- uid: System.ServiceModel.BasicHttpSecurity
  commentId: T:System.ServiceModel.BasicHttpSecurity
  id: BasicHttpSecurity
  parent: System.ServiceModel
  children:
  - System.ServiceModel.BasicHttpSecurity.Mode
  - System.ServiceModel.BasicHttpSecurity.Transport
  langs:
  - csharp
  - vb
  name: BasicHttpSecurity
  fullName: System.ServiceModel.BasicHttpSecurity
  type: Class
  source:
    remote:
      path: src/System.Private.ServiceModel/src/System/ServiceModel/BasicHttpSecurity.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: BasicHttpSecurity
    path: src/System.Private.ServiceModel/src/System/ServiceModel/BasicHttpSecurity.cs
    startLine: 10
  assemblies:
  - System.ServiceModel.Http
  namespace: System.ServiceModel
  summary: "\n<p>Configures the security settings of a <strong>basicHttpBinding</strong> binding.</p>\n"
  syntax:
    content: public sealed class BasicHttpSecurity
    content.vb: Public NotInheritable Class BasicHttpSecurity
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
  nameWithType: BasicHttpSecurity
- uid: System.ServiceModel.BasicHttpSecurity.Mode
  commentId: P:System.ServiceModel.BasicHttpSecurity.Mode
  id: Mode
  parent: System.ServiceModel.BasicHttpSecurity
  langs:
  - csharp
  - vb
  name: Mode
  fullName: System.ServiceModel.BasicHttpSecurity.Mode
  type: Property
  source:
    remote:
      path: src/System.Private.ServiceModel/src/System/ServiceModel/BasicHttpSecurity.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: Mode
    path: src/System.Private.ServiceModel/src/System/ServiceModel/BasicHttpSecurity.cs
    startLine: 28
  assemblies:
  - System.ServiceModel.Http
  namespace: System.ServiceModel
  summary: "\n<p>Gets or sets the security mode for a <strong>basicHttpBinding</strong> binding.</p>\n"
  syntax:
    content: public BasicHttpSecurityMode Mode { get; set; }
    content.vb: Public Property Mode As BasicHttpSecurityMode
    parameters: []
    return:
      type: System.ServiceModel.BasicHttpSecurityMode
      description: "\n<p>A value in the <xref href=\"System.ServiceModel.BasicHttpSecurityMode\" data-throw-if-not-resolved=\"false\"></xref> enumeration. The default value for this property is <xref href=\"System.ServiceModel.BasicHttpSecurityMode.None\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "\n<p>The value is not a legal value for <xref href=\"System.ServiceModel.BasicHttpSecurityMode\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  nameWithType: BasicHttpSecurity.Mode
- uid: System.ServiceModel.BasicHttpSecurity.Transport
  commentId: P:System.ServiceModel.BasicHttpSecurity.Transport
  id: Transport
  parent: System.ServiceModel.BasicHttpSecurity
  langs:
  - csharp
  - vb
  name: Transport
  fullName: System.ServiceModel.BasicHttpSecurity.Transport
  type: Property
  source:
    remote:
      path: src/System.Private.ServiceModel/src/System/ServiceModel/BasicHttpSecurity.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: Transport
    path: src/System.Private.ServiceModel/src/System/ServiceModel/BasicHttpSecurity.cs
    startLine: 41
  assemblies:
  - System.ServiceModel.Http
  namespace: System.ServiceModel
  summary: "\n<p>Gets the transport-level security settings for a <strong>basicHttpBinding</strong> binding.</p>\n"
  syntax:
    content: public HttpTransportSecurity Transport { get; set; }
    content.vb: Public Property Transport As HttpTransportSecurity
    parameters: []
    return:
      type: System.ServiceModel.HttpTransportSecurity
      description: "\n<p>The transport-level security settings for a <strong>basicHttpBinding</strong> binding.</p>\n"
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  nameWithType: BasicHttpSecurity.Transport
references:
- uid: System.ServiceModel
  isExternal: false
  name: System.ServiceModel
  fullName: System.ServiceModel
  nameWithType: System.ServiceModel
  commentId: N:System.ServiceModel
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
  nameWithType: Object
  commentId: T:System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  nameWithType: Object.ToString()
  commentId: M:System.Object.ToString
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  nameWithType: Object.Equals(Object)
  commentId: M:System.Object.Equals(System.Object)
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  nameWithType: Object.Equals(Object, Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  nameWithType: Object.ReferenceEquals(Object, Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  nameWithType: Object.GetHashCode()
  commentId: M:System.Object.GetHashCode
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  nameWithType: Object.GetType()
  commentId: M:System.Object.GetType
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  nameWithType: Object.MemberwiseClone()
  commentId: M:System.Object.MemberwiseClone
- uid: System
  isExternal: false
  name: System
  fullName: System
  nameWithType: System
  commentId: N:System
- uid: System.ServiceModel.BasicHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: BasicHttpSecurityMode
  fullName: System.ServiceModel.BasicHttpSecurityMode
  nameWithType: BasicHttpSecurityMode
  commentId: T:System.ServiceModel.BasicHttpSecurityMode
- uid: System.ServiceModel.HttpTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: HttpTransportSecurity
  fullName: System.ServiceModel.HttpTransportSecurity
  nameWithType: HttpTransportSecurity
  commentId: T:System.ServiceModel.HttpTransportSecurity
- uid: System.ArgumentOutOfRangeException
  isExternal: false
  name: ArgumentOutOfRangeException
  fullName: System.ArgumentOutOfRangeException
  nameWithType: ArgumentOutOfRangeException
  commentId: T:System.ArgumentOutOfRangeException
