### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.LocalClientSecuritySettings
  commentId: T:System.ServiceModel.Channels.LocalClientSecuritySettings
  id: LocalClientSecuritySettings
  parent: System.ServiceModel.Channels
  children:
  - System.ServiceModel.Channels.LocalClientSecuritySettings.#ctor
  - System.ServiceModel.Channels.LocalClientSecuritySettings.Clone
  - System.ServiceModel.Channels.LocalClientSecuritySettings.MaxClockSkew
  - System.ServiceModel.Channels.LocalClientSecuritySettings.ReplayWindow
  - System.ServiceModel.Channels.LocalClientSecuritySettings.TimestampValidityDuration
  langs:
  - csharp
  - vb
  name: LocalClientSecuritySettings
  nameWithType: LocalClientSecuritySettings
  fullName: System.ServiceModel.Channels.LocalClientSecuritySettings
  type: Class
  source:
    remote:
      path: src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: LocalClientSecuritySettings
    path: src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
    startLine: 37
  assemblies:
  - System.ServiceModel.Security
  namespace: System.ServiceModel.Channels
  summary: "\n<p>Specifies local client security settings.</p>\n"
  syntax:
    content: public sealed class LocalClientSecuritySettings
    content.vb: Public NotInheritable Class LocalClientSecuritySettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: System.ServiceModel.Channels.LocalClientSecuritySettings.#ctor
  commentId: M:System.ServiceModel.Channels.LocalClientSecuritySettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Channels.LocalClientSecuritySettings
  langs:
  - csharp
  - vb
  name: LocalClientSecuritySettings()
  nameWithType: LocalClientSecuritySettings.LocalClientSecuritySettings()
  fullName: System.ServiceModel.Channels.LocalClientSecuritySettings.LocalClientSecuritySettings()
  type: Constructor
  source:
    remote:
      path: src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: .ctor
    path: src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
    startLine: 39
  assemblies:
  - System.ServiceModel.Security
  namespace: System.ServiceModel.Channels
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.ServiceModel.Channels.LocalClientSecuritySettings\" data-throw-if-not-resolved=\"false\"></xref> class. </p>\n"
  syntax:
    content: public LocalClientSecuritySettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.ServiceModel.Channels.LocalClientSecuritySettings.MaxClockSkew
  commentId: P:System.ServiceModel.Channels.LocalClientSecuritySettings.MaxClockSkew
  id: MaxClockSkew
  parent: System.ServiceModel.Channels.LocalClientSecuritySettings
  langs:
  - csharp
  - vb
  name: MaxClockSkew
  nameWithType: LocalClientSecuritySettings.MaxClockSkew
  fullName: System.ServiceModel.Channels.LocalClientSecuritySettings.MaxClockSkew
  type: Property
  source:
    remote:
      path: src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: MaxClockSkew
    path: src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
    startLine: 40
  assemblies:
  - System.ServiceModel.Security
  namespace: System.ServiceModel.Channels
  summary: "\n<p>Gets or sets the maximum allowable time difference between the system clocks of the two parties that are communicating. </p>\n"
  syntax:
    content: public TimeSpan MaxClockSkew { get; set; }
    content.vb: Public Property MaxClockSkew As TimeSpan
    parameters: []
    return:
      type: System.TimeSpan
      description: "\n<p>A <xref href=\"System.TimeSpan\" data-throw-if-not-resolved=\"false\"></xref> that represents the maximum allowable time difference between the system clocks of the two parties that are communicating. The default is 5 minutes.</p>\n"
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "\n<p>The property is <strong>set</strong> to a value less than 0.</p>\n"
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.ServiceModel.Channels.LocalClientSecuritySettings.ReplayWindow
  commentId: P:System.ServiceModel.Channels.LocalClientSecuritySettings.ReplayWindow
  id: ReplayWindow
  parent: System.ServiceModel.Channels.LocalClientSecuritySettings
  langs:
  - csharp
  - vb
  name: ReplayWindow
  nameWithType: LocalClientSecuritySettings.ReplayWindow
  fullName: System.ServiceModel.Channels.LocalClientSecuritySettings.ReplayWindow
  type: Property
  source:
    remote:
      path: src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: ReplayWindow
    path: src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
    startLine: 41
  assemblies:
  - System.ServiceModel.Security
  namespace: System.ServiceModel.Channels
  summary: "\n<p>Gets or sets the maximum time that a message nonce is valid.</p>\n"
  syntax:
    content: public TimeSpan ReplayWindow { get; set; }
    content.vb: Public Property ReplayWindow As TimeSpan
    parameters: []
    return:
      type: System.TimeSpan
      description: "\n<p>A <xref href=\"System.TimeSpan\" data-throw-if-not-resolved=\"false\"></xref> that represents the maximum time that a message nonce is valid. The default is five minutes.</p>\n"
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "\n<p>The property is <strong>set</strong> to a value less than 0.</p>\n"
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.ServiceModel.Channels.LocalClientSecuritySettings.TimestampValidityDuration
  commentId: P:System.ServiceModel.Channels.LocalClientSecuritySettings.TimestampValidityDuration
  id: TimestampValidityDuration
  parent: System.ServiceModel.Channels.LocalClientSecuritySettings
  langs:
  - csharp
  - vb
  name: TimestampValidityDuration
  nameWithType: LocalClientSecuritySettings.TimestampValidityDuration
  fullName: System.ServiceModel.Channels.LocalClientSecuritySettings.TimestampValidityDuration
  type: Property
  source:
    remote:
      path: src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: TimestampValidityDuration
    path: src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
    startLine: 42
  assemblies:
  - System.ServiceModel.Security
  namespace: System.ServiceModel.Channels
  summary: "\n<p>Gets or sets the maximum duration that the messages are valid when sent by the client. If a message is received by the service after this duration, it should discard the message.</p>\n"
  syntax:
    content: public TimeSpan TimestampValidityDuration { get; set; }
    content.vb: Public Property TimestampValidityDuration As TimeSpan
    parameters: []
    return:
      type: System.TimeSpan
      description: "\n<p>A <xref href=\"System.TimeSpan\" data-throw-if-not-resolved=\"false\"></xref> that represents the maximum duration that the messages are valid when sent by the client. The default is 5 minutes.</p>\n"
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "\n<p>The property is <strong>set</strong> to a value less than 0.</p>\n"
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.ServiceModel.Channels.LocalClientSecuritySettings.Clone
  commentId: M:System.ServiceModel.Channels.LocalClientSecuritySettings.Clone
  id: Clone
  parent: System.ServiceModel.Channels.LocalClientSecuritySettings
  langs:
  - csharp
  - vb
  name: Clone()
  nameWithType: LocalClientSecuritySettings.Clone()
  fullName: System.ServiceModel.Channels.LocalClientSecuritySettings.Clone()
  type: Method
  source:
    remote:
      path: src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
      branch: master
      repo: https://github.com/dotnet/wcf.git
    id: Clone
    path: src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
    startLine: 43
  assemblies:
  - System.ServiceModel.Security
  namespace: System.ServiceModel.Channels
  summary: "\n<p>Creates a new instance of this class, which is a copy or clone of the current instance.</p>\n"
  syntax:
    content: public LocalClientSecuritySettings Clone()
    content.vb: Public Function Clone As LocalClientSecuritySettings
    return:
      type: System.ServiceModel.Channels.LocalClientSecuritySettings
      description: "\n<p>A new instance of <xref href=\"System.ServiceModel.Channels.LocalClientSecuritySettings\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.ServiceModel.Channels
  commentId: N:System.ServiceModel.Channels
  isExternal: false
  name: System.ServiceModel.Channels
  nameWithType: System.ServiceModel.Channels
  fullName: System.ServiceModel.Channels
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.TimeSpan
  commentId: T:System.TimeSpan
  parent: System
  isExternal: false
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Channels.LocalClientSecuritySettings
  commentId: T:System.ServiceModel.Channels.LocalClientSecuritySettings
  parent: System.ServiceModel.Channels
  isExternal: false
  name: LocalClientSecuritySettings
  nameWithType: LocalClientSecuritySettings
  fullName: System.ServiceModel.Channels.LocalClientSecuritySettings
- uid: System.ArgumentOutOfRangeException
  commentId: T:System.ArgumentOutOfRangeException
  isExternal: false
  name: ArgumentOutOfRangeException
  nameWithType: ArgumentOutOfRangeException
  fullName: System.ArgumentOutOfRangeException
