items:
- uid: Windows.UI.Xaml.Automation
  commentId: N:Windows.UI.Xaml.Automation
  id: Windows.UI.Xaml.Automation
  children:
  - Windows.UI.Xaml.Automation.ElementNotAvailableException
  - Windows.UI.Xaml.Automation.ElementNotEnabledException
  langs:
  - csharp
  - vb
  name: Windows.UI.Xaml.Automation
  fullName: Windows.UI.Xaml.Automation
  type: Namespace
  assemblies:
  - System.Runtime.WindowsRuntime.UI.Xaml
  summary: >-
    Defines the support types for Microsoft UI Automation infrastructure. These support types are for implementing Microsoft UI Automation support for a custom control.

    Also, AutomationProperties provides accessibility info as part of a XAML UI definition.
  nameWithType: Windows.UI.Xaml.Automation
references:
- uid: Windows.UI.Xaml.Automation.ElementNotAvailableException
  isExternal: false
  name: ElementNotAvailableException
  fullName: Windows.UI.Xaml.Automation.ElementNotAvailableException
  commentId: T:Windows.UI.Xaml.Automation.ElementNotAvailableException
  nameWithType: ElementNotAvailableException
- uid: Windows.UI.Xaml.Automation.ElementNotEnabledException
  isExternal: false
  name: ElementNotEnabledException
  fullName: Windows.UI.Xaml.Automation.ElementNotEnabledException
  commentId: T:Windows.UI.Xaml.Automation.ElementNotEnabledException
  nameWithType: ElementNotEnabledException
