items:
- uid: Windows.UI.Xaml.Automation
  commentId: N:Windows.UI.Xaml.Automation
  id: Windows.UI.Xaml.Automation
  children:
  - Windows.UI.Xaml.Automation.ElementNotAvailableException
  - Windows.UI.Xaml.Automation.ElementNotEnabledException
  langs:
  - csharp
  - vb
  name: Windows.UI.Xaml.Automation
  nameWithType: Windows.UI.Xaml.Automation
  fullName: Windows.UI.Xaml.Automation
  type: Namespace
  assemblies:
  - System.Runtime.WindowsRuntime.UI.Xaml
references:
- uid: Windows.UI.Xaml.Automation.ElementNotAvailableException
  commentId: T:Windows.UI.Xaml.Automation.ElementNotAvailableException
  isExternal: false
  name: ElementNotAvailableException
  nameWithType: ElementNotAvailableException
  fullName: Windows.UI.Xaml.Automation.ElementNotAvailableException
- uid: Windows.UI.Xaml.Automation.ElementNotEnabledException
  commentId: T:Windows.UI.Xaml.Automation.ElementNotEnabledException
  isExternal: false
  name: ElementNotEnabledException
  nameWithType: ElementNotEnabledException
  fullName: Windows.UI.Xaml.Automation.ElementNotEnabledException
